# ==============================================================================
# SETTINGS
# ==============================================================================
set -g mouse on
set -g focus-events on
set-window-option -g mode-keys vi

# ==============================================================================
# STATUS BAR (Dark+ theme)
# ==============================================================================
set -g status-style "bg=#1e1e1e,fg=#808080"
set -g status-justify centre
set -g status-left ""
set -g status-right ""
set -g window-status-format "#[fg=#808080]  #W  "
set -g window-status-current-format "#[fg=#ffffff,bold]  #W  "
set -g window-status-separator "│"
set -g status-format[0] "#[align=centre]#[fg=#569cd6,bold]#S  #[fg=#808080]│#{W:#{E:window-status-format},#{E:window-status-current-format}}"
